config/routes.rb
Rails.application.routes.draw do

 resources :users, only: [:create, :new, :show]

 resource :session, only: [:create, :new, :destroy]

 resources :bands do
   resources :albums, only: :new
 end

 resources :albums, except: [:index, :new] do
   resources :songs, only: :new
 end

 resources :songs, except: [:index, :new]

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, :album_name, presence: true
  

  belongs_to :Band

  has_many :songs

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :band_name, presence: true, uniqueness: true

  has_many :albums

  has_many :songs,
    through: :albums,
    source: :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :song_name, presence: true

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  end

app/models/user.rb
class User < ActiveRecord::Base

  validates :user_email, :hashword, :session_id, presence: true
  validates :user_email, uniqueness: true
  validates :password, length: {minimum: 1, allow_nil: true}

  after_initialize :set_session

  attr_reader :password

  def self.find_by_creds(email, pword)

    @user = User.find_by_user_email(email)
    return nil if @user.nil?
    return @user if BCrypt::Password.new(@user.hashword).is_password?(pword)

    nil
  end


  def password=(password)
    @password = password
    self.hashword = BCrypt::Password.create(password)
  end

  def set_session
    self.session_id = SecureRandom.urlsafe_base64(32)
  end

  def reset_session!
    self.session_id = SecureRandom.urlsafe_base64(32)
    self.save!
    self.session_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def logged_in?
    !!current_user
  end


  def current_user

    @current_user ||= User.find_by_session_id(session[:session_token])
    return @current_user unless @current_user.nil?

    nil
  end

  def login(user)
    user.reset_session!
    session[:session_token] = user.session_id
    redirect_to bands_url
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action do
    redirect_to new_session_url unless logged_in?
  end

  def index
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new band_params
    if @band.save
      redirect_to bands_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

private

  def band_params
    params.require(:band).permit(:band_name)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :sign_in
  end

  def create

    @user = User.find_by_creds(params[:user][:user_email], params[:user][:password])
    unless @user.nil?
      login(@user)

      # render text: login successful
    else
      flash.now[:errors] = ["Incorrect login credentials!"]
      @user= User.new(params.require(:user).permit(:user_email))
      render :sign_in
    end

  end

  def destroy
    current_user.reset_session!
    session[:session_token] = nil
    redirect_to new_session_url

  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)


    if @user.save
      login(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end

  def show
    render :show
  end



private

  def user_params
    params.require(:user).permit(:user_email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def safe_form
    <<-HTML.html_safe
      <input type="hidden" name="authenticity_token"
       value="#{form_authenticity_token}"       >
    HTML
  end

  def log_action

    # if current_user.nil?
    #   sign_in
    if logged_in?
      sign_out_button
    else
      sign_in_links
    end
  end

  def sign_in_links
    <<-HTML.html_safe
        <a href="#{new_session_url}">Sign in!</a>
       or
       <a href="#{new_user_url}">Sign up!</a>
    HTML
  end

  def sign_out_button
    <<-HTML.html_safe
    <form action="#{session_url}" method="POST">
      #{delete_it}
      #{safe_form}
      <button>Sign out</button>
    </form>
    HTML
  end


  def post_it
    rails_method(:push)
  end

  def put_it
    rails_method(:put)
  end

  def patch_it
    rails_method(:patch)
  end

  def delete_it
    rails_method(:delete)
  end

  def rails_method(type)
    <<-HTML.html_safe
      <input type="hidden" name="_method" value="#{type.to_s.upcase}">
    HTML
  end
end

app/views/bands/_band_form.html.erb
<!-- requires band, method -->

<form action="<%= bands_url %>", method="POST">
  <%= method = :post ? post_it : patch_it %>
  <%= safe_form %>
  <label>Band Name
    <input type="text" name="band[band_name]" value="<%=band.band_name%>">
  </label>
  <button>Rock On!</button>
</form>

app/views/bands/index.html.erb
 <%=  render 'shared/listify', listable: Band.all %>

app/views/bands/new.html.erb
<h2> Insert Band Here </h2>

<%= render 'band_form', {band: @band, method: :post} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Noterizr</title>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%=  render 'shared/heading' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/splash.html.erb
Under Construction

app/views/shared/_flash.html.erb
<ul>
  <font color="red">
  <% unless flash[:errors].nil? %>
    <% flash[:errors].each do |er| %>
      <li> <%= er %> </li>
    <% end %>
  <% end %>
</font>
</ul>

app/views/shared/_heading.html.erb
<%= log_action %>
<%= render 'shared/flash' %>
<h1>NOTERIZR::an_awseome_rails_music_app</h1> <br>

app/views/shared/_listify.html.erb
<!-- Requires listable -->

<h2> <%= listable.first.class.to_s.pluralize %> </h2>

<!-- Return One Level UP -->

  <ul>

    <% listable.each do |item| %>

    <li>
      <a href="<%= send((item.class.to_s.downcase + "_url"), item) %>">
        <%= item.send(item.class.to_s.downcase + "_name") %>
     </a>
   </li>

   <% end %>

   <li>
     <a href="<%= send("new_" + listable.first.class.to_s.downcase + "_url") %>">
       New
    </a>
  </li>
</ul>

app/views/shared/_login.html.erb
<!-- requires action, user, and mode locals -->
<form action="<%= action %>" method="POST">
  <%= safe_form %>
  <%= post_it %>
  <p>
    <label>E-mail
      <input type="text" name="user[user_email]" value="<%= user.user_email %>"
    </label>
  </p>

  <p>
    <label>Password
      <input type="password" name="user[password]">
    </label>
  </p>

  <button><%= mode %></button>

  </form>

app/views/users/new.html.erb
<%= render 'shared/login', mode: "Sign Up!", action: users_url, user: @user %>

app/views/users/show.html.erb
<p> current_user: <%= current_user.user_email %> </p>